CREATE TABLE promo_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  discount DECIMAL(5, 2) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  expires_at TIMESTAMP NOT NULL
);